export const CMSExttoMime ={
	".123"			: "application/vnd.lotus-1-2-3",
	".3dml"			: "text/vnd.in3d.3dml",
	".3g2"			: "video/3gpp2",
	".3gp"			: "video/3gpp",
	".a"			: "application/octet-stream",
	".aab"			: "application/x-authorware-bin",
	".aac"			: "audio/x-aac",
	".aam"			: "application/x-authorware-map",
	".aas"			: "application/x-authorware-seg",
	".abw"			: "application/x-abiword",
	".acc"			: "application/vnd.americandynamics.acc",
	".ace"			: "application/x-ace-compressed",
	".acu"			: "application/vnd.acucobol",
	".acutc"		: "application/vnd.acucorp",
	".adp"			: "audio/adpcm",
	".aep"			: "application/vnd.audiograph",
	".afm"			: "application/x-font-type1",
	".afp"			: "application/vnd.ibm.modcap",
	".ai"			: "application/postscript",
	".aif"			: "audio/x-aiff",
	".aifc"			: "audio/x-aiff",
	".aiff"			: "audio/x-aiff",
	".air"			: "application/vnd.adobe.air-application-installer-package+zip",
	".ami"			: "application/vnd.amiga.ami",
	".apk"			: "application/vnd.android.package-archive",
	".application"		: "application/x-ms-application",
	".apr"			: "application/vnd.lotus-approach",
	".asc"			: "application/pgp-signature",
	".asf"			: "video/x-ms-asf",
	".asm"			: "text/x-asm",
	".aso"			: "application/vnd.accpac.simply.aso",
	".asx"			: "video/x-ms-asf",
	".atc"			: "application/vnd.acucorp",
	".atom"			: "application/atom+xml",
	".atomcat"		: "application/atomcat+xml",
	".atomsvc"		: "application/atomsvc+xml",
	".atx"			: "application/vnd.antix.game-component",
	".au"			: "audio/basic",
	".avi"			: "video/x-msvideo",
	".aw"			: "application/applixware",
	".azf"			: "application/vnd.airzip.filesecure.azf",
	".azs"			: "application/vnd.airzip.filesecure.azs",
	".azw"			: "application/vnd.amazon.ebook",
	".bat"			: "application/x-msdownload",
	".bcpio"		: "application/x-bcpio",
	".bdf"			: "application/x-font-bdf",
	".bdm"			: "application/vnd.syncml.dm+wbxml",
	".bh2"			: "application/vnd.fujitsu.oasysprs",
	".bin"			: "application/octet-stream",
	".bmi"			: "application/vnd.bmi",
	".bmp"			: "image/bmp",
	".book"			: "application/vnd.framemaker",
	".box"			: "application/vnd.previewsystems.box",
	".boz"			: "application/x-bzip2",
	".bpk"			: "application/octet-stream",
	".btif"			: "image/prs.btif",
	".bz"			: "application/x-bzip",
	".bz2"			: "application/x-bzip2",
	".c"			: "text/x-c",
	".c4d"			: "application/vnd.clonk.c4group",
	".c4f"			: "application/vnd.clonk.c4group",
	".c4g"			: "application/vnd.clonk.c4group",
	".c4p"			: "application/vnd.clonk.c4group",
	".c4u"			: "application/vnd.clonk.c4group",
	".cab"			: "application/vnd.ms-cab-compressed",
	".car"			: "application/vnd.curl.car",
	".cat"			: "application/vnd.ms-pki.seccat",
	".cc"			: "text/x-c",
	".cct"			: "application/x-director",
	".ccxml"		: "application/ccxml+xml",
	".cdbcmsg"		: "application/vnd.contact.cmsg",
	".cdf"			: "application/x-netcdf",
	".cdkey"		: "application/vnd.mediastation.cdkey",
	".cdx"			: "chemical/x-cdx",
	".cdxml"		: "application/vnd.chemdraw+xml",
	".cdy"			: "application/vnd.cinderella",
	".cer"			: "application/pkix-cert",
	".cgm"			: "image/cgm",
	".chat"			: "application/x-chat",
	".chm"			: "application/vnd.ms-htmlhelp",
	".chrt"			: "application/vnd.kde.kchart",
	".cif"			: "chemical/x-cif",
	".cii"			: "application/vnd.anser-web-certificate-issue-initiation",
	".cil"			: "application/vnd.ms-artgalry",
	".cla"			: "application/vnd.claymore",
	".class"		: "application/java-vm",
	".clkk"			: "application/vnd.crick.clicker.keyboard",
	".clkp"			: "application/vnd.crick.clicker.palette",
	".clkt"			: "application/vnd.crick.clicker.template",
	".clkw"			: "application/vnd.crick.clicker.wordbank",
	".clkx"			: "application/vnd.crick.clicker",
	".clp"			: "application/x-msclip",
	".cmc"			: "application/vnd.cosmocaller",
	".cmdf"			: "chemical/x-cmdf",
	".cml"			: "chemical/x-cml",
	".cmp"			: "application/vnd.yellowriver-custom-menu",
	".cmx"			: "image/x-cmx",
	".cod"			: "application/vnd.rim.cod",
	".com"			: "application/x-msdownload",
	".conf"			: "text/plain",
	".cpio"			: "application/x-cpio",
	".cpp"			: "text/x-c",
	".cpt"			: "application/mac-compactpro",
	".crd"			: "application/x-mscardfile",
	".crl"			: "application/pkix-crl",
	".crt"			: "application/x-x509-ca-cert",
	".csh"			: "application/x-csh",
	".csml"			: "chemical/x-csml",
	".csp"			: "application/vnd.commonspace",
	".css"			: "text/css",
	".cst"			: "application/x-director",
	".csv"			: "text/csv",
	".cu"			: "application/cu-seeme",
	".curl"			: "text/vnd.curl",
	".cww"			: "application/prs.cww",
	".cxt"			: "application/x-director",
	".cxx"			: "text/x-c",
	".daf"			: "application/vnd.mobius.daf",
	".dataless"		: "application/vnd.fdsn.seed",
	".davmount"		: "application/davmount+xml",
	".dcr"			: "application/x-director",
	".dcurl"		: "text/vnd.curl.dcurl",
	".dd2"			: "application/vnd.oma.dd2+xml",
	".ddd"			: "application/vnd.fujixerox.ddd",
	".deb"			: "application/x-debian-package",
	".def"			: "text/plain",
	".deploy"		: "application/octet-stream",
	".der"			: "application/x-x509-ca-cert",
	".dfac"			: "application/vnd.dreamfactory",
	".dic"			: "text/x-c",
	".diff"			: "text/plain",
	".dir"			: "application/x-director",
	".dis"			: "application/vnd.mobius.dis",
	".dist"			: "application/octet-stream",
	".distz"		: "application/octet-stream",
	".djv"			: "image/vnd.djvu",
	".djvu"			: "image/vnd.djvu",
	".dll"			: "application/x-msdownload",
	".dmg"			: "application/octet-stream",
	".dms"			: "application/octet-stream",
	".dna"			: "application/vnd.dna",
	".doc"			: "application/msword",
	".docm"			: "application/vnd.ms-word.document.macroenabled.12",
	".docx"			: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	".dot"			: "application/msword",
	".dotm"			: "application/vnd.ms-word.template.macroenabled.12",
	".dotx"			: "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
	".dp"			: "application/vnd.osgi.dp",
	".dpg"			: "application/vnd.dpgraph",
	".dsc"			: "text/prs.lines.tag",
	".dtb"			: "application/x-dtbook+xml",
	".dtd"			: "application/xml-dtd",
	".dts"			: "audio/vnd.dts",
	".dtshd"		: "audio/vnd.dts.hd",
	".dump"			: "application/octet-stream",
	".dvi"			: "application/x-dvi",
	".dwf"			: "model/vnd.dwf",
	".dwg"			: "image/vnd.dwg",
	".dxf"			: "image/vnd.dxf",
	".dxp"			: "application/vnd.spotfire.dxp",
	".dxr"			: "application/x-director",
	".ecelp4800"		: "audio/vnd.nuera.ecelp4800",
	".ecelp7470"		: "audio/vnd.nuera.ecelp7470",
	".ecelp9600"		: "audio/vnd.nuera.ecelp9600",
	".ecma"			: "application/ecmascript",
	".edm"			: "application/vnd.novadigm.edm",
	".edx"			: "application/vnd.novadigm.edx",
	".efif"			: "application/vnd.picsel",
	".ei6"			: "application/vnd.pg.osasli",
	".elc"			: "application/octet-stream",
	".eml"			: "message/rfc822",
	".emma"			: "application/emma+xml",
	".eol"			: "audio/vnd.digital-winds",
	".eot"			: "application/vnd.ms-fontobject",
	".eps"			: "application/postscript",
	".epub"			: "application/epub+zip",
	".es3"			: "application/vnd.eszigno3+xml",
	".esf"			: "application/vnd.epson.esf",
	".et3"			: "application/vnd.eszigno3+xml",
	".etx"			: "text/x-setext",
	".exe"			: "application/x-msdownload",
	".ext"			: "application/vnd.novadigm.ext",
	".ez"			: "application/andrew-inset",
	".ez2"			: "application/vnd.ezpix-album",
	".ez3"			: "application/vnd.ezpix-package",
	".f"			: "text/x-fortran",
	".f4v"			: "video/x-f4v",
	".f77"			: "text/x-fortran",
	".f90"			: "text/x-fortran",
	".fbs"			: "image/vnd.fastbidsheet",
	".fdf"			: "application/vnd.fdf",
	".fe_launch"		: "application/vnd.denovo.fcselayout-link",
	".fg5"			: "application/vnd.fujitsu.oasysgp",
	".fgd"			: "application/x-director",
	".fh"			: "image/x-freehand",
	".fh4"			: "image/x-freehand",
	".fh5"			: "image/x-freehand",
	".fh7"			: "image/x-freehand",
	".fhc"			: "image/x-freehand",
	".fig"			: "application/x-xfig",
	".fli"			: "video/x-fli",
	".flo"			: "application/vnd.micrografx.flo",
	".flv"			: "video/x-flv",
	".flw"			: "application/vnd.kde.kivio",
	".flx"			: "text/vnd.fmi.flexstor",
	".fly"			: "text/vnd.fly",
	".fm"			: "application/vnd.framemaker",
	".fnc"			: "application/vnd.frogans.fnc",
	".for"			: "text/x-fortran",
	".fpx"			: "image/vnd.fpx",
	".frame"		: "application/vnd.framemaker",
	".fsc"			: "application/vnd.fsc.weblaunch",
	".fst"			: "image/vnd.fst",
	".ftc"			: "application/vnd.fluxtime.clip",
	".fti"			: "application/vnd.anser-web-funds-transfer-initiation",
	".fvt"			: "video/vnd.fvt",
	".fzs"			: "application/vnd.fuzzysheet",
	".g3"			: "image/g3fax",
	".gac"			: "application/vnd.groove-account",
	".gdl"			: "model/vnd.gdl",
	".geo"			: "application/vnd.dynageo",
	".gex"			: "application/vnd.geometry-explorer",
	".ggb"			: "application/vnd.geogebra.file",
	".ggt"			: "application/vnd.geogebra.tool",
	".ghf"			: "application/vnd.groove-help",
	".gif"			: "image/gif",
	".gim"			: "application/vnd.groove-identity-message",
	".gmx"			: "application/vnd.gmx",
	".gnumeric"		: "application/x-gnumeric",
	".gph"			: "application/vnd.flographit",
	".gqf"			: "application/vnd.grafeq",
	".gqs"			: "application/vnd.grafeq",
	".gram"			: "application/srgs",
	".gre"			: "application/vnd.geometry-explorer",
	".grv"			: "application/vnd.groove-injector",
	".grxml"		: "application/srgs+xml",
	".gsf"			: "application/x-font-ghostscript",
	".gtar"			: "application/x-gtar",
	".gtm"			: "application/vnd.groove-tool-message",
	".gtw"			: "model/vnd.gtw",
	".gv"			: "text/vnd.graphviz",
	".gz"			: "application/x-gzip",
	".h"			: "text/x-c",
	".h261"			: "video/h261",
	".h263"			: "video/h263",
	".h264"			: "video/h264",
	".hbci"			: "application/vnd.hbci",
	".hdf"			: "application/x-hdf",
	".hh"			: "text/x-c",
	".hlp"			: "application/winhlp",
	".hpgl"			: "application/vnd.hp-hpgl",
	".hpid"			: "application/vnd.hp-hpid",
	".hps"			: "application/vnd.hp-hps",
	".hqx"			: "application/mac-binhex40",
	".htke"			: "application/vnd.kenameaapp",
	".htm"			: "text/html",
	".html"			: "text/html",
	".hvd"			: "application/vnd.yamaha.hv-dic",
	".hvp"			: "application/vnd.yamaha.hv-voice",
	".hvs"			: "application/vnd.yamaha.hv-script",
	".icc"			: "application/vnd.iccprofile",
	".ice"			: "x-conference/x-cooltalk",
	".icm"			: "application/vnd.iccprofile",
	".ico"			: "image/x-icon",
	".ics"			: "text/calendar",
	".ief"			: "image/ief",
	".ifb"			: "text/calendar",
	".ifm"			: "application/vnd.shana.informed.formdata",
	".iges"			: "model/iges",
	".igl"			: "application/vnd.igloader",
	".igs"			: "model/iges",
	".igx"			: "application/vnd.micrografx.igx",
	".iif"			: "application/vnd.shana.informed.interchange",
	".imp"			: "application/vnd.accpac.simply.imp",
	".ims"			: "application/vnd.ms-ims",
	".in"			: "text/plain",
	".ipk"			: "application/vnd.shana.informed.package",
	".irm"			: "application/vnd.ibm.rights-management",
	".irp"			: "application/vnd.irepository.package+xml",
	".iso"			: "application/octet-stream",
	".itp"			: "application/vnd.shana.informed.formtemplate",
	".ivp"			: "application/vnd.immervision-ivp",
	".ivu"			: "application/vnd.immervision-ivu",
	".jad"			: "text/vnd.sun.j2me.app-descriptor",
	".jam"			: "application/vnd.jam",
	".jar"			: "application/java-archive",
	".java"			: "text/x-java-source",
	".jisp"			: "application/vnd.jisp",
	".jlt"			: "application/vnd.hp-jlyt",
	".jnlp"			: "application/x-java-jnlp-file",
	".joda"			: "application/vnd.joost.joda-archive",
	".jpe"			: "image/jpeg",
	".jpeg"			: "image/jpeg",
	".jpg"			: "image/jpeg",
	".jpgm"			: "video/jpm",
	".jpgv"			: "video/jpeg",
	".jpm"			: "video/jpm",
	".js"			: "application/javascript",
	".json"			: "application/json",
	".kar"			: "audio/midi",
	".karbon"		: "application/vnd.kde.karbon",
	".kfo"			: "application/vnd.kde.kformula",
	".kia"			: "application/vnd.kidspiration",
	".kil"			: "application/x-killustrator",
	".kml"			: "application/vnd.google-earth.kml+xml",
	".kmz"			: "application/vnd.google-earth.kmz",
	".kne"			: "application/vnd.kinar",
	".knp"			: "application/vnd.kinar",
	".kon"			: "application/vnd.kde.kontour",
	".kpr"			: "application/vnd.kde.kpresenter",
	".kpt"			: "application/vnd.kde.kpresenter",
	".ksh"			: "text/plain",
	".ksp"			: "application/vnd.kde.kspread",
	".ktr"			: "application/vnd.kahootz",
	".ktz"			: "application/vnd.kahootz",
	".kwd"			: "application/vnd.kde.kword",
	".kwt"			: "application/vnd.kde.kword",
	".latex"		: "application/x-latex",
	".lbd"			: "application/vnd.llamagraphics.life-balance.desktop",
	".lbe"			: "application/vnd.llamagraphics.life-balance.exchange+xml",
	".les"			: "application/vnd.hhe.lesson-player",
	".lha"			: "application/octet-stream",
	".link66"		: "application/vnd.route66.link66+xml",
	".list"			: "text/plain",
	".list3820"		: "application/vnd.ibm.modcap",
	".listafp"		: "application/vnd.ibm.modcap",
	".log"			: "text/plain",
	".lostxml"		: "application/lost+xml",
	".lrf"			: "application/octet-stream",
	".lrm"			: "application/vnd.ms-lrm",
	".ltf"			: "application/vnd.frogans.ltf",
	".lvp"			: "audio/vnd.lucent.voice",
	".lwp"			: "application/vnd.lotus-wordpro",
	".lzh"			: "application/octet-stream",
	".m13"			: "application/x-msmediaview",
	".m14"			: "application/x-msmediaview",
	".m1v"			: "video/mpeg",
	".m2a"			: "audio/mpeg",
	".m2v"			: "video/mpeg",
	".m3a"			: "audio/mpeg",
	".m3u"			: "audio/x-mpegurl",
	".m4u"			: "video/vnd.mpegurl",
	".m4v"			: "video/x-m4v",
	".ma"			: "application/mathematica",
	".mag"			: "application/vnd.ecowin.chart",
	".maker"		: "application/vnd.framemaker",
	".man"			: "text/troff",
	".mathml"		: "application/mathml+xml",
	".mb"			: "application/mathematica",
	".mbk"			: "application/vnd.mobius.mbk",
	".mbox"			: "application/mbox",
	".mc1"			: "application/vnd.medcalcdata",
	".mcd"			: "application/vnd.mcd",
	".mcurl"		: "text/vnd.curl.mcurl",
	".mdb"			: "application/x-msaccess",
	".mdi"			: "image/vnd.ms-modi",
	".me"			: "text/troff",
	".mesh"			: "model/mesh",
	".mfm"			: "application/vnd.mfmp",
	".mgz"			: "application/vnd.proteus.magazine",
	".mht"			: "message/rfc822",
	".mhtml"		: "message/rfc822",
	".mid"			: "audio/midi",
	".midi"			: "audio/midi",
	".mif"			: "application/vnd.mif",
	".mime"			: "message/rfc822",
	".mj2"			: "video/mj2",
	".mjp2"			: "video/mj2",
	".mlp"			: "application/vnd.dolby.mlp",
	".mmd"			: "application/vnd.chipnuts.karaoke-mmd",
	".mmf"			: "application/vnd.smaf",
	".mmr"			: "image/vnd.fujixerox.edmics-mmr",
	".mny"			: "application/x-msmoney",
	".mobi"			: "application/x-mobipocket-ebook",
	".mov"			: "video/quicktime",
	".movie"		: "video/x-sgi-movie",
	".mp2"			: "audio/mpeg",
	".mp2a"			: "audio/mpeg",
	".mp3"			: "audio/mpeg",
	".mp4"			: "video/mp4",
	".mp4a"			: "audio/mp4",
	".mp4s"			: "application/mp4",
	".mp4v"			: "video/mp4",
	".mpa"			: "video/mpeg",
	".mpc"			: "application/vnd.mophun.certificate",
	".mpe"			: "video/mpeg",
	".mpeg"			: "video/mpeg",
	".mpg"			: "video/mpeg",
	".mpg4"			: "video/mp4",
	".mpga"			: "audio/mpeg",
	".mpkg"			: "application/vnd.apple.installer+xml",
	".mpm"			: "application/vnd.blueice.multipass",
	".mpn"			: "application/vnd.mophun.application",
	".mpp"			: "application/vnd.ms-project",
	".mpt"			: "application/vnd.ms-project",
	".mpy"			: "application/vnd.ibm.minipay",
	".mqy"			: "application/vnd.mobius.mqy",
	".mrc"			: "application/marc",
	".ms"			: "text/troff",
	".mscml"		: "application/mediaservercontrol+xml",
	".mseed"		: "application/vnd.fdsn.mseed",
	".mseq"			: "application/vnd.mseq",
	".msf"			: "application/vnd.epson.msf",
	".msh"			: "model/mesh",
	".msi"			: "application/x-msdownload",
	".msl"			: "application/vnd.mobius.msl",
	".msty"			: "application/vnd.muvee.style",
	".mts"			: "model/vnd.mts",
	".mus"			: "application/vnd.musician",
	".musicxml"		: "application/vnd.recordare.musicxml+xml",
	".mvb"			: "application/x-msmediaview",
	".mwf"			: "application/vnd.mfer",
	".mxf"			: "application/mxf",
	".mxl"			: "application/vnd.recordare.musicxml",
	".mxml"			: "application/xv+xml",
	".mxs"			: "application/vnd.triscape.mxs",
	".mxu"			: "video/vnd.mpegurl",
	".n-gage"		: "application/vnd.nokia.n-gage.symbian.install",
	".nb"			: "application/mathematica",
	".nc"			: "application/x-netcdf",
	".ncx"			: "application/x-dtbncx+xml",
	".ngdat"		: "application/vnd.nokia.n-gage.data",
	".nlu"			: "application/vnd.neurolanguage.nlu",
	".nml"			: "application/vnd.enliven",
	".nnd"			: "application/vnd.noblenet-directory",
	".nns"			: "application/vnd.noblenet-sealer",
	".nnw"			: "application/vnd.noblenet-web",
	".npx"			: "image/vnd.net-fpx",
	".nsf"			: "application/vnd.lotus-notes",
	".nws"			: "message/rfc822",
	".o"			: "application/octet-stream",
	".oa2"			: "application/vnd.fujitsu.oasys2",
	".oa3"			: "application/vnd.fujitsu.oasys3",
	".oas"			: "application/vnd.fujitsu.oasys",
	".obd"			: "application/x-msbinder",
	".obj"			: "application/octet-stream",
	".oda"			: "application/oda",
	".odb"			: "application/vnd.oasis.opendocument.database",
	".odc"			: "application/vnd.oasis.opendocument.chart",
	".odf"			: "application/vnd.oasis.opendocument.formula",
	".odft"			: "application/vnd.oasis.opendocument.formula-template",
	".odg"			: "application/vnd.oasis.opendocument.graphics",
	".odi"			: "application/vnd.oasis.opendocument.image",
	".odp"			: "application/vnd.oasis.opendocument.presentation",
	".ods"			: "application/vnd.oasis.opendocument.spreadsheet",
	".odt"			: "application/vnd.oasis.opendocument.text",
	".oga"			: "audio/ogg",
	".ogg"			: "audio/ogg",
	".ogv"			: "video/ogg",
	".ogx"			: "application/ogg",
	".onepkg"		: "application/onenote",
	".onetmp"		: "application/onenote",
	".onetoc"		: "application/onenote",
	".onetoc2"		: "application/onenote",
	".opf"			: "application/oebps-package+xml",
	".oprc"			: "application/vnd.palm",
	".org"			: "application/vnd.lotus-organizer",
	".osf"			: "application/vnd.yamaha.openscoreformat",
	".osfpvg"		: "application/vnd.yamaha.openscoreformat.osfpvg+xml",
	".otc"			: "application/vnd.oasis.opendocument.chart-template",
	".otf"			: "application/x-font-otf",
	".otg"			: "application/vnd.oasis.opendocument.graphics-template",
	".oth"			: "application/vnd.oasis.opendocument.text-web",
	".oti"			: "application/vnd.oasis.opendocument.image-template",
	".otm"			: "application/vnd.oasis.opendocument.text-master",
	".otp"			: "application/vnd.oasis.opendocument.presentation-template",
	".ots"			: "application/vnd.oasis.opendocument.spreadsheet-template",
	".ott"			: "application/vnd.oasis.opendocument.text-template",
	".oxt"			: "application/vnd.openofficeorg.extension",
	".p"			: "text/x-pascal",
	".p10"			: "application/pkcs10",
	".p12"			: "application/x-pkcs12",
	".p7b"			: "application/x-pkcs7-certificates",
	".p7c"			: "application/pkcs7-mime",
	".p7m"			: "application/pkcs7-mime",
	".p7r"			: "application/x-pkcs7-certreqresp",
	".p7s"			: "application/pkcs7-signature",
	".pas"			: "text/x-pascal",
	".pbd"			: "application/vnd.powerbuilder6",
	".pbm"			: "image/x-portable-bitmap",
	".pcf"			: "application/x-font-pcf",
	".pcl"			: "application/vnd.hp-pcl",
	".pclxl"		: "application/vnd.hp-pclxl",
	".pct"			: "image/x-pict",
	".pcurl"		: "application/vnd.curl.pcurl",
	".pcx"			: "image/x-pcx",
	".pdb"			: "application/vnd.palm",
	".pdf"			: "application/pdf",
	".pfa"			: "application/x-font-type1",
	".pfb"			: "application/x-font-type1",
	".pfm"			: "application/x-font-type1",
	".pfr"			: "application/font-tdpfr",
	".pfx"			: "application/x-pkcs12",
	".pgm"			: "image/x-portable-graymap",
	".pgn"			: "application/x-chess-pgn",
	".pgp"			: "application/pgp-encrypted",
	".pic"			: "image/x-pict",
	".pkg"			: "application/octet-stream",
	".pki"			: "application/pkixcmp",
	".pkipath"		: "application/pkix-pkipath",
	".pl"			: "text/plain",
	".plb"			: "application/vnd.3gpp.pic-bw-large",
	".plc"			: "application/vnd.mobius.plc",
	".plf"			: "application/vnd.pocketlearn",
	".pls"			: "application/pls+xml",
	".pml"			: "application/vnd.ctc-posml",
	".png"			: "image/png",
	".pnm"			: "image/x-portable-anymap",
	".portpkg"		: "application/vnd.macports.portpkg",
	".pot"			: "application/vnd.ms-powerpoint",
	".potm"			: "application/vnd.ms-powerpoint.template.macroenabled.12",
	".potx"			: "application/vnd.openxmlformats-officedocument.presentationml.template",
	".ppa"			: "application/vnd.ms-powerpoint",
	".ppam"			: "application/vnd.ms-powerpoint.addin.macroenabled.12",
	".ppd"			: "application/vnd.cups-ppd",
	".ppm"			: "image/x-portable-pixmap",
	".pps"			: "application/vnd.ms-powerpoint",
	".ppsm"			: "application/vnd.ms-powerpoint.slideshow.macroenabled.12",
	".ppsx"			: "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
	".ppt"			: "application/vnd.ms-powerpoint",
	".pptm"			: "application/vnd.ms-powerpoint.presentation.macroenabled.12",
	".pptx"			: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	".pqa"			: "application/vnd.palm",
	".prc"			: "application/x-mobipocket-ebook",
	".pre"			: "application/vnd.lotus-freelance",
	".prf"			: "application/pics-rules",
	".ps"			: "application/postscript",
	".psb"			: "application/vnd.3gpp.pic-bw-small",
	".psd"			: "image/vnd.adobe.photoshop",
	".psf"			: "application/x-font-linux-psf",
	".ptid"			: "application/vnd.pvi.ptid1",
	".pub"			: "application/x-mspublisher",
	".pvb"			: "application/vnd.3gpp.pic-bw-var",
	".pwn"			: "application/vnd.3m.post-it-notes",
	".pwz"			: "application/vnd.ms-powerpoint",
	".py"			: "text/x-python",
	".pya"			: "audio/vnd.ms-playready.media.pya",
	".pyc"			: "application/x-python-code",
	".pyo"			: "application/x-python-code",
	".pyv"			: "video/vnd.ms-playready.media.pyv",
	".qam"			: "application/vnd.epson.quickanime",
	".qbo"			: "application/vnd.intu.qbo",
	".qfx"			: "application/vnd.intu.qfx",
	".qps"			: "application/vnd.publishare-delta-tree",
	".qt"			: "video/quicktime",
	".qwd"			: "application/vnd.quark.quarkxpress",
	".qwt"			: "application/vnd.quark.quarkxpress",
	".qxb"			: "application/vnd.quark.quarkxpress",
	".qxd"			: "application/vnd.quark.quarkxpress",
	".qxl"			: "application/vnd.quark.quarkxpress",
	".qxt"			: "application/vnd.quark.quarkxpress",
	".ra"			: "audio/x-pn-realaudio",
	".ram"			: "audio/x-pn-realaudio",
	".rar"			: "application/x-rar-compressed",
	".ras"			: "image/x-cmu-raster",
	".rcprofile"		: "application/vnd.ipunplugged.rcprofile",
	".rdf"			: "application/rdf+xml",
	".rdz"			: "application/vnd.data-vision.rdz",
	".rep"			: "application/vnd.businessobjects",
	".res"			: "application/x-dtbresource+xml",
	".rgb"			: "image/x-rgb",
	".rif"			: "application/reginfo+xml",
	".rl"			: "application/resource-lists+xml",
	".rlc"			: "image/vnd.fujixerox.edmics-rlc",
	".rld"			: "application/resource-lists-diff+xml",
	".rm"			: "application/vnd.rn-realmedia",
	".rmi"			: "audio/midi",
	".rmp"			: "audio/x-pn-realaudio-plugin",
	".rms"			: "application/vnd.jcp.javame.midlet-rms",
	".rnc"			: "application/relax-ng-compact-syntax",
	".roff"			: "text/troff",
	".rpm"			: "application/x-rpm",
	".rpss"			: "application/vnd.nokia.radio-presets",
	".rpst"			: "application/vnd.nokia.radio-preset",
	".rq"			: "application/sparql-query",
	".rs"			: "application/rls-services+xml",
	".rsd"			: "application/rsd+xml",
	".rss"			: "application/rss+xml",
	".rtf"			: "application/rtf",
	".rtx"			: "text/richtext",
	".s"			: "text/x-asm",
	".saf"			: "application/vnd.yamaha.smaf-audio",
	".sbml"			: "application/sbml+xml",
	".sc"			: "application/vnd.ibm.secure-container",
	".scd"			: "application/x-msschedule",
	".scm"			: "application/vnd.lotus-screencam",
	".scq"			: "application/scvp-cv-request",
	".scs"			: "application/scvp-cv-response",
	".scurl"		: "text/vnd.curl.scurl",
	".sda"			: "application/vnd.stardivision.draw",
	".sdc"			: "application/vnd.stardivision.calc",
	".sdd"			: "application/vnd.stardivision.impress",
	".sdkd"			: "application/vnd.solent.sdkm+xml",
	".sdkm"			: "application/vnd.solent.sdkm+xml",
	".sdp"			: "application/sdp",
	".sdw"			: "application/vnd.stardivision.writer",
	".see"			: "application/vnd.seemail",
	".seed"			: "application/vnd.fdsn.seed",
	".sema"			: "application/vnd.sema",
	".semd"			: "application/vnd.semd",
	".semf"			: "application/vnd.semf",
	".ser"			: "application/java-serialized-object",
	".setpay"		: "application/set-payment-initiation",
	".setreg"		: "application/set-registration-initiation",
	".sfd-hdstx"		: "application/vnd.hydrostatix.sof-data",
	".sfs"			: "application/vnd.spotfire.sfs",
	".sgl"			: "application/vnd.stardivision.writer-global",
	".sgm"			: "text/sgml",
	".sgml"			: "text/sgml",
	".sh"			: "application/x-sh",
	".shar"			: "application/x-shar",
	".shf"			: "application/shf+xml",
	".si"			: "text/vnd.wap.si",
	".sic"			: "application/vnd.wap.sic",
	".sig"			: "application/pgp-signature",
	".silo"			: "model/mesh",
	".sis"			: "application/vnd.symbian.install",
	".sisx"			: "application/vnd.symbian.install",
	".sit"			: "application/x-stuffit",
	".sitx"			: "application/x-stuffitx",
	".skd"			: "application/vnd.koan",
	".skm"			: "application/vnd.koan",
	".skp"			: "application/vnd.koan",
	".skt"			: "application/vnd.koan",
	".sl"			: "text/vnd.wap.sl",
	".slc"			: "application/vnd.wap.slc",
	".sldm"			: "application/vnd.ms-powerpoint.slide.macroenabled.12",
	".sldx"			: "application/vnd.openxmlformats-officedocument.presentationml.slide",
	".slt"			: "application/vnd.epson.salt",
	".smf"			: "application/vnd.stardivision.math",
	".smi"			: "application/smil+xml",
	".smil"			: "application/smil+xml",
	".snd"			: "audio/basic",
	".snf"			: "application/x-font-snf",
	".so"			: "application/octet-stream",
	".spc"			: "application/x-pkcs7-certificates",
	".spf"			: "application/vnd.yamaha.smaf-phrase",
	".spl"			: "application/x-futuresplash",
	".spot"			: "text/vnd.in3d.spot",
	".spp"			: "application/scvp-vp-response",
	".spq"			: "application/scvp-vp-request",
	".spx"			: "audio/ogg",
	".src"			: "application/x-wais-source",
	".srx"			: "application/sparql-results+xml",
	".sse"			: "application/vnd.kodak-descriptor",
	".ssf"			: "application/vnd.epson.ssf",
	".ssml"			: "application/ssml+xml",
	".stc"			: "application/vnd.sun.xml.calc.template",
	".std"			: "application/vnd.sun.xml.draw.template",
	".stf"			: "application/vnd.wt.stf",
	".sti"			: "application/vnd.sun.xml.impress.template",
	".stk"			: "application/hyperstudio",
	".stl"			: "application/vnd.ms-pki.stl",
	".str"			: "application/vnd.pg.format",
	".stw"			: "application/vnd.sun.xml.writer.template",
	".sus"			: "application/vnd.sus-calendar",
	".susp"			: "application/vnd.sus-calendar",
	".sv4cpio"		: "application/x-sv4cpio",
	".sv4crc"		: "application/x-sv4crc",
	".svd"			: "application/vnd.svd",
	".svg"			: "image/svg+xml",
	".svgz"			: "image/svg+xml",
	".swa"			: "application/x-director",
	".swf"			: "application/x-shockwave-flash",
	".swi"			: "application/vnd.arastra.swi",
	".sxc"			: "application/vnd.sun.xml.calc",
	".sxd"			: "application/vnd.sun.xml.draw",
	".sxg"			: "application/vnd.sun.xml.writer.global",
	".sxi"			: "application/vnd.sun.xml.impress",
	".sxm"			: "application/vnd.sun.xml.math",
	".sxw"			: "application/vnd.sun.xml.writer",
	".t"			: "text/troff",
	".tao"			: "application/vnd.tao.intent-module-archive",
	".tar"			: "application/x-tar",
	".tcap"			: "application/vnd.3gpp2.tcap",
	".tcl"			: "application/x-tcl",
	".teacher"		: "application/vnd.smart.teacher",
	".tex"			: "application/x-tex",
	".texi"			: "application/x-texinfo",
	".texinfo"		: "application/x-texinfo",
	".text"			: "text/plain",
	".tfm"			: "application/x-tex-tfm",
	".tgz"			: "application/x-gzip",
	".tif"			: "image/tiff",
	".tiff"			: "image/tiff",
	".tmo"			: "application/vnd.tmobile-livetv",
	".torrent"		: "application/x-bittorrent",
	".tpl"			: "application/vnd.groove-tool-template",
	".tpt"			: "application/vnd.trid.tpt",
	".tr"			: "text/troff",
	".tra"			: "application/vnd.trueapp",
	".trm"			: "application/x-msterminal",
	".tsv"			: "text/tab-separated-values",
	".ttc"			: "application/x-font-ttf",
	".ttf"			: "application/x-font-ttf",
	".twd"			: "application/vnd.simtech-mindmapper",
	".twds"			: "application/vnd.simtech-mindmapper",
	".txd"			: "application/vnd.genomatix.tuxedo",
	".txf"			: "application/vnd.mobius.txf",
	".txt"			: "text/plain",
	".u32"			: "application/x-authorware-bin",
	".udeb"			: "application/x-debian-package",
	".ufd"			: "application/vnd.ufdl",
	".ufdl"			: "application/vnd.ufdl",
	".umj"			: "application/vnd.umajin",
	".unityweb"		: "application/vnd.unity",
	".uoml"			: "application/vnd.uoml+xml",
	".uri"			: "text/uri-list",
	".uris"			: "text/uri-list",
	".urls"			: "text/uri-list",
	".ustar"		: "application/x-ustar",
	".utz"			: "application/vnd.uiq.theme",
	".uu"			: "text/x-uuencode",
	".vcd"			: "application/x-cdlink",
	".vcf"			: "text/x-vcard",
	".vcg"			: "application/vnd.groove-vcard",
	".vcs"			: "text/x-vcalendar",
	".vcx"			: "application/vnd.vcx",
	".vis"			: "application/vnd.visionary",
	".viv"			: "video/vnd.vivo",
	".vor"			: "application/vnd.stardivision.writer",
	".vox"			: "application/x-authorware-bin",
	".vrml"			: "model/vrml",
	".vsd"			: "application/vnd.visio",
	".vsf"			: "application/vnd.vsf",
	".vss"			: "application/vnd.visio",
	".vst"			: "application/vnd.visio",
	".vsw"			: "application/vnd.visio",
	".vtu"			: "model/vnd.vtu",
	".vxml"			: "application/voicexml+xml",
	".w3d"			: "application/x-director",
	".wad"			: "application/x-doom",
	".wav"			: "audio/x-wav",
	".wax"			: "audio/x-ms-wax",
	".wbmp"			: "image/vnd.wap.wbmp",
	".wbs"			: "application/vnd.criticaltools.wbs+xml",
	".wbxml"		: "application/vnd.wap.wbxml",
	".wcm"			: "application/vnd.ms-works",
	".wdb"			: "application/vnd.ms-works",
	".wiz"			: "application/msword",
	".wks"			: "application/vnd.ms-works",
	".wm"			: "video/x-ms-wm",
	".wma"			: "audio/x-ms-wma",
	".wmd"			: "application/x-ms-wmd",
	".wmf"			: "application/x-msmetafile",
	".wml"			: "text/vnd.wap.wml",
	".wmlc"			: "application/vnd.wap.wmlc",
	".wmls"			: "text/vnd.wap.wmlscript",
	".wmlsc"		: "application/vnd.wap.wmlscriptc",
	".wmv"			: "video/x-ms-wmv",
	".wmx"			: "video/x-ms-wmx",
	".wmz"			: "application/x-ms-wmz",
	".wpd"			: "application/vnd.wordperfect",
	".wpl"			: "application/vnd.ms-wpl",
	".wps"			: "application/vnd.ms-works",
	".wqd"			: "application/vnd.wqd",
	".wri"			: "application/x-mswrite",
	".wrl"			: "model/vrml",
	".wsdl"			: "application/wsdl+xml",
	".wspolicy"		: "application/wspolicy+xml",
	".wtb"			: "application/vnd.webturbo",
	".wvx"			: "video/x-ms-wvx",
	".x32"			: "application/x-authorware-bin",
	".x3d"			: "application/vnd.hzn-3d-crossword",
	".xap"			: "application/x-silverlight-app",
	".xar"			: "application/vnd.xara",
	".xbap"			: "application/x-ms-xbap",
	".xbd"			: "application/vnd.fujixerox.docuworks.binder",
	".xbm"			: "image/x-xbitmap",
	".xdm"			: "application/vnd.syncml.dm+xml",
	".xdp"			: "application/vnd.adobe.xdp+xml",
	".xdw"			: "application/vnd.fujixerox.docuworks",
	".xenc"			: "application/xenc+xml",
	".xer"			: "application/patch-ops-error+xml",
	".xfdf"			: "application/vnd.adobe.xfdf",
	".xfdl"			: "application/vnd.xfdl",
	".xht"			: "application/xhtml+xml",
	".xhtml"		: "application/xhtml+xml",
	".xhvml"		: "application/xv+xml",
	".xif"			: "image/vnd.xiff",
	".xla"			: "application/vnd.ms-excel",
	".xlam"			: "application/vnd.ms-excel.addin.macroenabled.12",
	".xlb"			: "application/vnd.ms-excel",
	".xlc"			: "application/vnd.ms-excel",
	".xlm"			: "application/vnd.ms-excel",
	".xls"			: "application/vnd.ms-excel",
	".xlsb"			: "application/vnd.ms-excel.sheet.binary.macroenabled.12",
	".xlsm"			: "application/vnd.ms-excel.sheet.macroenabled.12",
	".xlsx"			: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	".xlt"			: "application/vnd.ms-excel",
	".xltm"			: "application/vnd.ms-excel.template.macroenabled.12",
	".xltx"			: "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
	".xlw"			: "application/vnd.ms-excel",
	".xml"			: "application/xml",
	".xo"			: "application/vnd.olpc-sugar",
	".xop"			: "application/xop+xml",
	".xpdl"			: "application/xml",
	".xpi"			: "application/x-xpinstall",
	".xpm"			: "image/x-xpixmap",
	".xpr"			: "application/vnd.is-xpr",
	".xps"			: "application/vnd.ms-xpsdocument",
	".xpw"			: "application/vnd.intercon.formnet",
	".xpx"			: "application/vnd.intercon.formnet",
	".xsl"			: "application/xml",
	".xslt"			: "application/xslt+xml",
	".xsm"			: "application/vnd.syncml+xml",
	".xspf"			: "application/xspf+xml",
	".xul"			: "application/vnd.mozilla.xul+xml",
	".xvm"			: "application/xv+xml",
	".xvml"			: "application/xv+xml",
	".xwd"			: "image/x-xwindowdump",
	".xyz"			: "chemical/x-xyz",
	".zaz"			: "application/vnd.zzazz.deck+xml",
	".zip"			: "application/zip",
	".zir"			: "application/vnd.zul",
	".zirz"			: "application/vnd.zul",
	".zmm"			: "application/vnd.handheld-entertainment+xml"
};

export const CMSMimeToExtension ={
"application/vnd.lotus-1-2-3"	:	".123"	,
"text/vnd.in3d.3dml"	:	".3dml"	,
"video/3gpp2"	:	".3g2"	,
"video/3gpp"	:	".3gp"	,
"application/octet-stream"	:	".a"	,
"application/x-authorware-bin"	:	".aab"	,
"audio/x-aac"	:	".aac"	,
"application/x-authorware-map"	:	".aam"	,
"application/x-authorware-seg"	:	".aas"	,
"application/x-abiword"	:	".abw"	,
"application/vnd.americandynamics.acc"	:	".acc"	,
"application/x-ace-compressed"	:	".ace"	,
"application/vnd.acucobol"	:	".acu"	,
"application/vnd.acucorp"	:	".acutc"	,
"audio/adpcm"	:	".adp"	,
"application/vnd.audiograph"	:	".aep"	,
"application/x-font-type1"	:	".afm"	,
"application/vnd.ibm.modcap"	:	".afp"	,
"application/postscript"	:	".ai"	,
"audio/x-aiff"	:	".aif"	,
"audio/x-aiff"	:	".aifc"	,
"audio/x-aiff"	:	".aiff"	,
"application/vnd.adobe.air-application-installer-package+zip"	:	".air"	,
"application/vnd.amiga.ami"	:	".ami"	,
"application/vnd.android.package-archive"	:	".apk"	,
"application/x-ms-application"	:	".application"	,
"application/vnd.lotus-approach"	:	".apr"	,
"application/pgp-signature"	:	".asc"	,
"video/x-ms-asf"	:	".asf"	,
"text/x-asm"	:	".asm"	,
"application/vnd.accpac.simply.aso"	:	".aso"	,
"video/x-ms-asf"	:	".asx"	,
"application/vnd.acucorp"	:	".atc"	,
"application/atom+xml"	:	".atom"	,
"application/atomcat+xml"	:	".atomcat"	,
"application/atomsvc+xml"	:	".atomsvc"	,
"application/vnd.antix.game-component"	:	".atx"	,
"audio/basic"	:	".au"	,
"video/x-msvideo"	:	".avi"	,
"application/applixware"	:	".aw"	,
"application/vnd.airzip.filesecure.azf"	:	".azf"	,
"application/vnd.airzip.filesecure.azs"	:	".azs"	,
"application/vnd.amazon.ebook"	:	".azw"	,
"application/x-msdownload"	:	".bat"	,
"application/x-bcpio"	:	".bcpio"	,
"application/x-font-bdf"	:	".bdf"	,
"application/vnd.syncml.dm+wbxml"	:	".bdm"	,
"application/vnd.fujitsu.oasysprs"	:	".bh2"	,
"application/octet-stream"	:	".bin"	,
"application/vnd.bmi"	:	".bmi"	,
"image/bmp"	:	".bmp"	,
"application/vnd.framemaker"	:	".book"	,
"application/vnd.previewsystems.box"	:	".box"	,
"application/x-bzip2"	:	".boz"	,
"application/octet-stream"	:	".bpk"	,
"image/prs.btif"	:	".btif"	,
"application/x-bzip"	:	".bz"	,
"application/x-bzip2"	:	".bz2"	,
"text/x-c"	:	".c"	,
"application/vnd.clonk.c4group"	:	".c4d"	,
"application/vnd.clonk.c4group"	:	".c4f"	,
"application/vnd.clonk.c4group"	:	".c4g"	,
"application/vnd.clonk.c4group"	:	".c4p"	,
"application/vnd.clonk.c4group"	:	".c4u"	,
"application/vnd.ms-cab-compressed"	:	".cab"	,
"application/vnd.curl.car"	:	".car"	,
"application/vnd.ms-pki.seccat"	:	".cat"	,
"text/x-c"	:	".cc"	,
"application/x-director"	:	".cct"	,
"application/ccxml+xml"	:	".ccxml"	,
"application/vnd.contact.cmsg"	:	".cdbcmsg"	,
"application/x-netcdf"	:	".cdf"	,
"application/vnd.mediastation.cdkey"	:	".cdkey"	,
"chemical/x-cdx"	:	".cdx"	,
"application/vnd.chemdraw+xml"	:	".cdxml"	,
"application/vnd.cinderella"	:	".cdy"	,
"application/pkix-cert"	:	".cer"	,
"image/cgm"	:	".cgm"	,
"application/x-chat"	:	".chat"	,
"application/vnd.ms-htmlhelp"	:	".chm"	,
"application/vnd.kde.kchart"	:	".chrt"	,
"chemical/x-cif"	:	".cif"	,
"application/vnd.anser-web-certificate-issue-initiation"	:	".cii"	,
"application/vnd.ms-artgalry"	:	".cil"	,
"application/vnd.claymore"	:	".cla"	,
"application/java-vm"	:	".class"	,
"application/vnd.crick.clicker.keyboard"	:	".clkk"	,
"application/vnd.crick.clicker.palette"	:	".clkp"	,
"application/vnd.crick.clicker.template"	:	".clkt"	,
"application/vnd.crick.clicker.wordbank"	:	".clkw"	,
"application/vnd.crick.clicker"	:	".clkx"	,
"application/x-msclip"	:	".clp"	,
"application/vnd.cosmocaller"	:	".cmc"	,
"chemical/x-cmdf"	:	".cmdf"	,
"chemical/x-cml"	:	".cml"	,
"application/vnd.yellowriver-custom-menu"	:	".cmp"	,
"image/x-cmx"	:	".cmx"	,
"application/vnd.rim.cod"	:	".cod"	,
"application/x-msdownload"	:	".com"	,
"text/plain"	:	".conf"	,
"application/x-cpio"	:	".cpio"	,
"text/x-c"	:	".cpp"	,
"application/mac-compactpro"	:	".cpt"	,
"application/x-mscardfile"	:	".crd"	,
"application/pkix-crl"	:	".crl"	,
"application/x-x509-ca-cert"	:	".crt"	,
"application/x-csh"	:	".csh"	,
"chemical/x-csml"	:	".csml"	,
"application/vnd.commonspace"	:	".csp"	,
"text/css"	:	".css"	,
"application/x-director"	:	".cst"	,
"text/csv"	:	".csv"	,
"application/cu-seeme"	:	".cu"	,
"text/vnd.curl"	:	".curl"	,
"application/prs.cww"	:	".cww"	,
"application/x-director"	:	".cxt"	,
"text/x-c"	:	".cxx"	,
"application/vnd.mobius.daf"	:	".daf"	,
"application/vnd.fdsn.seed"	:	".dataless"	,
"application/davmount+xml"	:	".davmount"	,
"application/x-director"	:	".dcr"	,
"text/vnd.curl.dcurl"	:	".dcurl"	,
"application/vnd.oma.dd2+xml"	:	".dd2"	,
"application/vnd.fujixerox.ddd"	:	".ddd"	,
"application/x-debian-package"	:	".deb"	,
"text/plain"	:	".def"	,
"application/octet-stream"	:	".deploy"	,
"application/x-x509-ca-cert"	:	".der"	,
"application/vnd.dreamfactory"	:	".dfac"	,
"text/x-c"	:	".dic"	,
"text/plain"	:	".diff"	,
"application/x-director"	:	".dir"	,
"application/vnd.mobius.dis"	:	".dis"	,
"application/octet-stream"	:	".dist"	,
"application/octet-stream"	:	".distz"	,
"image/vnd.djvu"	:	".djv"	,
"image/vnd.djvu"	:	".djvu"	,
"application/x-msdownload"	:	".dll"	,
"application/octet-stream"	:	".dmg"	,
"application/octet-stream"	:	".dms"	,
"application/vnd.dna"	:	".dna"	,
"application/msword"	:	".doc"	,
"application/vnd.ms-word.document.macroenabled.12"	:	".docm"	,
"application/vnd.openxmlformats-officedocument.wordprocessingml.document"	:	".docx"	,
"application/msword"	:	".dot"	,
"application/vnd.ms-word.template.macroenabled.12"	:	".dotm"	,
"application/vnd.openxmlformats-officedocument.wordprocessingml.template"	:	".dotx"	,
"application/vnd.osgi.dp"	:	".dp"	,
"application/vnd.dpgraph"	:	".dpg"	,
"text/prs.lines.tag"	:	".dsc"	,
"application/x-dtbook+xml"	:	".dtb"	,
"application/xml-dtd"	:	".dtd"	,
"audio/vnd.dts"	:	".dts"	,
"audio/vnd.dts.hd"	:	".dtshd"	,
"application/octet-stream"	:	".dump"	,
"application/x-dvi"	:	".dvi"	,
"model/vnd.dwf"	:	".dwf"	,
"image/vnd.dwg"	:	".dwg"	,
"image/vnd.dxf"	:	".dxf"	,
"application/vnd.spotfire.dxp"	:	".dxp"	,
"application/x-director"	:	".dxr"	,
"audio/vnd.nuera.ecelp4800"	:	".ecelp4800"	,
"audio/vnd.nuera.ecelp7470"	:	".ecelp7470"	,
"audio/vnd.nuera.ecelp9600"	:	".ecelp9600"	,
"application/ecmascript"	:	".ecma"	,
"application/vnd.novadigm.edm"	:	".edm"	,
"application/vnd.novadigm.edx"	:	".edx"	,
"application/vnd.picsel"	:	".efif"	,
"application/vnd.pg.osasli"	:	".ei6"	,
"application/octet-stream"	:	".elc"	,
"message/rfc822"	:	".eml"	,
"application/emma+xml"	:	".emma"	,
"audio/vnd.digital-winds"	:	".eol"	,
"application/vnd.ms-fontobject"	:	".eot"	,
"application/postscript"	:	".eps"	,
"application/epub+zip"	:	".epub"	,
"application/vnd.eszigno3+xml"	:	".es3"	,
"application/vnd.epson.esf"	:	".esf"	,
"application/vnd.eszigno3+xml"	:	".et3"	,
"text/x-setext"	:	".etx"	,
"application/x-msdownload"	:	".exe"	,
"application/vnd.novadigm.ext"	:	".ext"	,
"application/andrew-inset"	:	".ez"	,
"application/vnd.ezpix-album"	:	".ez2"	,
"application/vnd.ezpix-package"	:	".ez3"	,
"text/x-fortran"	:	".f"	,
"video/x-f4v"	:	".f4v"	,
"text/x-fortran"	:	".f77"	,
"text/x-fortran"	:	".f90"	,
"image/vnd.fastbidsheet"	:	".fbs"	,
"application/vnd.fdf"	:	".fdf"	,
"application/vnd.denovo.fcselayout-link"	:	".fe_launch"	,
"application/vnd.fujitsu.oasysgp"	:	".fg5"	,
"application/x-director"	:	".fgd"	,
"image/x-freehand"	:	".fh"	,
"image/x-freehand"	:	".fh4"	,
"image/x-freehand"	:	".fh5"	,
"image/x-freehand"	:	".fh7"	,
"image/x-freehand"	:	".fhc"	,
"application/x-xfig"	:	".fig"	,
"video/x-fli"	:	".fli"	,
"application/vnd.micrografx.flo"	:	".flo"	,
"video/x-flv"	:	".flv"	,
"application/vnd.kde.kivio"	:	".flw"	,
"text/vnd.fmi.flexstor"	:	".flx"	,
"text/vnd.fly"	:	".fly"	,
"application/vnd.framemaker"	:	".fm"	,
"application/vnd.frogans.fnc"	:	".fnc"	,
"text/x-fortran"	:	".for"	,
"image/vnd.fpx"	:	".fpx"	,
"application/vnd.framemaker"	:	".frame"	,
"application/vnd.fsc.weblaunch"	:	".fsc"	,
"image/vnd.fst"	:	".fst"	,
"application/vnd.fluxtime.clip"	:	".ftc"	,
"application/vnd.anser-web-funds-transfer-initiation"	:	".fti"	,
"video/vnd.fvt"	:	".fvt"	,
"application/vnd.fuzzysheet"	:	".fzs"	,
"image/g3fax"	:	".g3"	,
"application/vnd.groove-account"	:	".gac"	,
"model/vnd.gdl"	:	".gdl"	,
"application/vnd.dynageo"	:	".geo"	,
"application/vnd.geometry-explorer"	:	".gex"	,
"application/vnd.geogebra.file"	:	".ggb"	,
"application/vnd.geogebra.tool"	:	".ggt"	,
"application/vnd.groove-help"	:	".ghf"	,
"image/gif"	:	".gif"	,
"application/vnd.groove-identity-message"	:	".gim"	,
"application/vnd.gmx"	:	".gmx"	,
"application/x-gnumeric"	:	".gnumeric"	,
"application/vnd.flographit"	:	".gph"	,
"application/vnd.grafeq"	:	".gqf"	,
"application/vnd.grafeq"	:	".gqs"	,
"application/srgs"	:	".gram"	,
"application/vnd.geometry-explorer"	:	".gre"	,
"application/vnd.groove-injector"	:	".grv"	,
"application/srgs+xml"	:	".grxml"	,
"application/x-font-ghostscript"	:	".gsf"	,
"application/x-gtar"	:	".gtar"	,
"application/vnd.groove-tool-message"	:	".gtm"	,
"model/vnd.gtw"	:	".gtw"	,
"text/vnd.graphviz"	:	".gv"	,
"application/x-gzip"	:	".gz"	,
"text/x-c"	:	".h"	,
"video/h261"	:	".h261"	,
"video/h263"	:	".h263"	,
"video/h264"	:	".h264"	,
"application/vnd.hbci"	:	".hbci"	,
"application/x-hdf"	:	".hdf"	,
"text/x-c"	:	".hh"	,
"application/winhlp"	:	".hlp"	,
"application/vnd.hp-hpgl"	:	".hpgl"	,
"application/vnd.hp-hpid"	:	".hpid"	,
"application/vnd.hp-hps"	:	".hps"	,
"application/mac-binhex40"	:	".hqx"	,
"application/vnd.kenameaapp"	:	".htke"	,
"text/html"	:	".htm"	,
"text/html"	:	".html"	,
"application/vnd.yamaha.hv-dic"	:	".hvd"	,
"application/vnd.yamaha.hv-voice"	:	".hvp"	,
"application/vnd.yamaha.hv-script"	:	".hvs"	,
"application/vnd.iccprofile"	:	".icc"	,
"x-conference/x-cooltalk"	:	".ice"	,
"application/vnd.iccprofile"	:	".icm"	,
"image/x-icon"	:	".ico"	,
"text/calendar"	:	".ics"	,
"image/ief"	:	".ief"	,
"text/calendar"	:	".ifb"	,
"application/vnd.shana.informed.formdata"	:	".ifm"	,
"model/iges"	:	".iges"	,
"application/vnd.igloader"	:	".igl"	,
"model/iges"	:	".igs"	,
"application/vnd.micrografx.igx"	:	".igx"	,
"application/vnd.shana.informed.interchange"	:	".iif"	,
"application/vnd.accpac.simply.imp"	:	".imp"	,
"application/vnd.ms-ims"	:	".ims"	,
"text/plain"	:	".in"	,
"application/vnd.shana.informed.package"	:	".ipk"	,
"application/vnd.ibm.rights-management"	:	".irm"	,
"application/vnd.irepository.package+xml"	:	".irp"	,
"application/octet-stream"	:	".iso"	,
"application/vnd.shana.informed.formtemplate"	:	".itp"	,
"application/vnd.immervision-ivp"	:	".ivp"	,
"application/vnd.immervision-ivu"	:	".ivu"	,
"text/vnd.sun.j2me.app-descriptor"	:	".jad"	,
"application/vnd.jam"	:	".jam"	,
"application/java-archive"	:	".jar"	,
"text/x-java-source"	:	".java"	,
"application/vnd.jisp"	:	".jisp"	,
"application/vnd.hp-jlyt"	:	".jlt"	,
"application/x-java-jnlp-file"	:	".jnlp"	,
"application/vnd.joost.joda-archive"	:	".joda"	,
"image/jpeg"	:	".jpe"	,
"image/jpeg"	:	".jpeg"	,
"image/jpeg"	:	".jpg"	,
"video/jpm"	:	".jpgm"	,
"video/jpeg"	:	".jpgv"	,
"video/jpm"	:	".jpm"	,
"application/javascript"	:	".js"	,
"application/json"	:	".json"	,
"audio/midi"	:	".kar"	,
"application/vnd.kde.karbon"	:	".karbon"	,
"application/vnd.kde.kformula"	:	".kfo"	,
"application/vnd.kidspiration"	:	".kia"	,
"application/x-killustrator"	:	".kil"	,
"application/vnd.google-earth.kml+xml"	:	".kml"	,
"application/vnd.google-earth.kmz"	:	".kmz"	,
"application/vnd.kinar"	:	".kne"	,
"application/vnd.kinar"	:	".knp"	,
"application/vnd.kde.kontour"	:	".kon"	,
"application/vnd.kde.kpresenter"	:	".kpr"	,
"application/vnd.kde.kpresenter"	:	".kpt"	,
"text/plain"	:	".ksh"	,
"application/vnd.kde.kspread"	:	".ksp"	,
"application/vnd.kahootz"	:	".ktr"	,
"application/vnd.kahootz"	:	".ktz"	,
"application/vnd.kde.kword"	:	".kwd"	,
"application/vnd.kde.kword"	:	".kwt"	,
"application/x-latex"	:	".latex"	,
"application/vnd.llamagraphics.life-balance.desktop"	:	".lbd"	,
"application/vnd.llamagraphics.life-balance.exchange+xml"	:	".lbe"	,
"application/vnd.hhe.lesson-player"	:	".les"	,
"application/octet-stream"	:	".lha"	,
"application/vnd.route66.link66+xml"	:	".link66"	,
"text/plain"	:	".list"	,
"application/vnd.ibm.modcap"	:	".list3820"	,
"application/vnd.ibm.modcap"	:	".listafp"	,
"text/plain"	:	".log"	,
"application/lost+xml"	:	".lostxml"	,
"application/octet-stream"	:	".lrf"	,
"application/vnd.ms-lrm"	:	".lrm"	,
"application/vnd.frogans.ltf"	:	".ltf"	,
"audio/vnd.lucent.voice"	:	".lvp"	,
"application/vnd.lotus-wordpro"	:	".lwp"	,
"application/octet-stream"	:	".lzh"	,
"application/x-msmediaview"	:	".m13"	,
"application/x-msmediaview"	:	".m14"	,
"video/mpeg"	:	".m1v"	,
"audio/mpeg"	:	".m2a"	,
"video/mpeg"	:	".m2v"	,
"audio/mpeg"	:	".m3a"	,
"audio/x-mpegurl"	:	".m3u"	,
"video/vnd.mpegurl"	:	".m4u"	,
"video/x-m4v"	:	".m4v"	,
"application/mathematica"	:	".ma"	,
"application/vnd.ecowin.chart"	:	".mag"	,
"application/vnd.framemaker"	:	".maker"	,
"text/troff"	:	".man"	,
"application/mathml+xml"	:	".mathml"	,
"application/mathematica"	:	".mb"	,
"application/vnd.mobius.mbk"	:	".mbk"	,
"application/mbox"	:	".mbox"	,
"application/vnd.medcalcdata"	:	".mc1"	,
"application/vnd.mcd"	:	".mcd"	,
"text/vnd.curl.mcurl"	:	".mcurl"	,
"application/x-msaccess"	:	".mdb"	,
"image/vnd.ms-modi"	:	".mdi"	,
"text/troff"	:	".me"	,
"model/mesh"	:	".mesh"	,
"application/vnd.mfmp"	:	".mfm"	,
"application/vnd.proteus.magazine"	:	".mgz"	,
"message/rfc822"	:	".mht"	,
"message/rfc822"	:	".mhtml"	,
"audio/midi"	:	".mid"	,
"audio/midi"	:	".midi"	,
"application/vnd.mif"	:	".mif"	,
"message/rfc822"	:	".mime"	,
"video/mj2"	:	".mj2"	,
"video/mj2"	:	".mjp2"	,
"application/vnd.dolby.mlp"	:	".mlp"	,
"application/vnd.chipnuts.karaoke-mmd"	:	".mmd"	,
"application/vnd.smaf"	:	".mmf"	,
"image/vnd.fujixerox.edmics-mmr"	:	".mmr"	,
"application/x-msmoney"	:	".mny"	,
"application/x-mobipocket-ebook"	:	".mobi"	,
"video/quicktime"	:	".mov"	,
"video/x-sgi-movie"	:	".movie"	,
"audio/mpeg"	:	".mp2"	,
"audio/mpeg"	:	".mp2a"	,
"audio/mpeg"	:	".mp3"	,
"video/mp4"	:	".mp4"	,
"audio/mp4"	:	".mp4a"	,
"application/mp4"	:	".mp4s"	,
"video/mp4"	:	".mp4v"	,
"video/mpeg"	:	".mpa"	,
"application/vnd.mophun.certificate"	:	".mpc"	,
"video/mpeg"	:	".mpe"	,
"video/mpeg"	:	".mpeg"	,
"video/mpeg"	:	".mpg"	,
"video/mp4"	:	".mpg4"	,
"audio/mpeg"	:	".mpga"	,
"application/vnd.apple.installer+xml"	:	".mpkg"	,
"application/vnd.blueice.multipass"	:	".mpm"	,
"application/vnd.mophun.application"	:	".mpn"	,
"application/vnd.ms-project"	:	".mpp"	,
"application/vnd.ms-project"	:	".mpt"	,
"application/vnd.ibm.minipay"	:	".mpy"	,
"application/vnd.mobius.mqy"	:	".mqy"	,
"application/marc"	:	".mrc"	,
"text/troff"	:	".ms"	,
"application/mediaservercontrol+xml"	:	".mscml"	,
"application/vnd.fdsn.mseed"	:	".mseed"	,
"application/vnd.mseq"	:	".mseq"	,
"application/vnd.epson.msf"	:	".msf"	,
"model/mesh"	:	".msh"	,
"application/x-msdownload"	:	".msi"	,
"application/vnd.mobius.msl"	:	".msl"	,
"application/vnd.muvee.style"	:	".msty"	,
"model/vnd.mts"	:	".mts"	,
"application/vnd.musician"	:	".mus"	,
"application/vnd.recordare.musicxml+xml"	:	".musicxml"	,
"application/x-msmediaview"	:	".mvb"	,
"application/vnd.mfer"	:	".mwf"	,
"application/mxf"	:	".mxf"	,
"application/vnd.recordare.musicxml"	:	".mxl"	,
"application/xv+xml"	:	".mxml"	,
"application/vnd.triscape.mxs"	:	".mxs"	,
"video/vnd.mpegurl"	:	".mxu"	,
"application/vnd.nokia.n-gage.symbian.install"	:	".n-gage"	,
"application/mathematica"	:	".nb"	,
"application/x-netcdf"	:	".nc"	,
"application/x-dtbncx+xml"	:	".ncx"	,
"application/vnd.nokia.n-gage.data"	:	".ngdat"	,
"application/vnd.neurolanguage.nlu"	:	".nlu"	,
"application/vnd.enliven"	:	".nml"	,
"application/vnd.noblenet-directory"	:	".nnd"	,
"application/vnd.noblenet-sealer"	:	".nns"	,
"application/vnd.noblenet-web"	:	".nnw"	,
"image/vnd.net-fpx"	:	".npx"	,
"application/vnd.lotus-notes"	:	".nsf"	,
"message/rfc822"	:	".nws"	,
"application/octet-stream"	:	".o"	,
"application/vnd.fujitsu.oasys2"	:	".oa2"	,
"application/vnd.fujitsu.oasys3"	:	".oa3"	,
"application/vnd.fujitsu.oasys"	:	".oas"	,
"application/x-msbinder"	:	".obd"	,
"application/octet-stream"	:	".obj"	,
"application/oda"	:	".oda"	,
"application/vnd.oasis.opendocument.database"	:	".odb"	,
"application/vnd.oasis.opendocument.chart"	:	".odc"	,
"application/vnd.oasis.opendocument.formula"	:	".odf"	,
"application/vnd.oasis.opendocument.formula-template"	:	".odft"	,
"application/vnd.oasis.opendocument.graphics"	:	".odg"	,
"application/vnd.oasis.opendocument.image"	:	".odi"	,
"application/vnd.oasis.opendocument.presentation"	:	".odp"	,
"application/vnd.oasis.opendocument.spreadsheet"	:	".ods"	,
"application/vnd.oasis.opendocument.text"	:	".odt"	,
"audio/ogg"	:	".oga"	,
"audio/ogg"	:	".ogg"	,
"video/ogg"	:	".ogv"	,
"application/ogg"	:	".ogx"	,
"application/onenote"	:	".onepkg"	,
"application/onenote"	:	".onetmp"	,
"application/onenote"	:	".onetoc"	,
"application/onenote"	:	".onetoc2"	,
"application/oebps-package+xml"	:	".opf"	,
"application/vnd.palm"	:	".oprc"	,
"application/vnd.lotus-organizer"	:	".org"	,
"application/vnd.yamaha.openscoreformat"	:	".osf"	,
"application/vnd.yamaha.openscoreformat.osfpvg+xml"	:	".osfpvg"	,
"application/vnd.oasis.opendocument.chart-template"	:	".otc"	,
"application/x-font-otf"	:	".otf"	,
"application/vnd.oasis.opendocument.graphics-template"	:	".otg"	,
"application/vnd.oasis.opendocument.text-web"	:	".oth"	,
"application/vnd.oasis.opendocument.image-template"	:	".oti"	,
"application/vnd.oasis.opendocument.text-master"	:	".otm"	,
"application/vnd.oasis.opendocument.presentation-template"	:	".otp"	,
"application/vnd.oasis.opendocument.spreadsheet-template"	:	".ots"	,
"application/vnd.oasis.opendocument.text-template"	:	".ott"	,
"application/vnd.openofficeorg.extension"	:	".oxt"	,
"text/x-pascal"	:	".p"	,
"application/pkcs10"	:	".p10"	,
"application/x-pkcs12"	:	".p12"	,
"application/x-pkcs7-certificates"	:	".p7b"	,
"application/pkcs7-mime"	:	".p7c"	,
"application/pkcs7-mime"	:	".p7m"	,
"application/x-pkcs7-certreqresp"	:	".p7r"	,
"application/pkcs7-signature"	:	".p7s"	,
"text/x-pascal"	:	".pas"	,
"application/vnd.powerbuilder6"	:	".pbd"	,
"image/x-portable-bitmap"	:	".pbm"	,
"application/x-font-pcf"	:	".pcf"	,
"application/vnd.hp-pcl"	:	".pcl"	,
"application/vnd.hp-pclxl"	:	".pclxl"	,
"image/x-pict"	:	".pct"	,
"application/vnd.curl.pcurl"	:	".pcurl"	,
"image/x-pcx"	:	".pcx"	,
"application/vnd.palm"	:	".pdb"	,
"application/pdf"	:	".pdf"	,
"application/x-font-type1"	:	".pfa"	,
"application/x-font-type1"	:	".pfb"	,
"application/x-font-type1"	:	".pfm"	,
"application/font-tdpfr"	:	".pfr"	,
"application/x-pkcs12"	:	".pfx"	,
"image/x-portable-graymap"	:	".pgm"	,
"application/x-chess-pgn"	:	".pgn"	,
"application/pgp-encrypted"	:	".pgp"	,
"image/x-pict"	:	".pic"	,
"application/octet-stream"	:	".pkg"	,
"application/pkixcmp"	:	".pki"	,
"application/pkix-pkipath"	:	".pkipath"	,
"text/plain"	:	".pl"	,
"application/vnd.3gpp.pic-bw-large"	:	".plb"	,
"application/vnd.mobius.plc"	:	".plc"	,
"application/vnd.pocketlearn"	:	".plf"	,
"application/pls+xml"	:	".pls"	,
"application/vnd.ctc-posml"	:	".pml"	,
"image/png"	:	".png"	,
"image/x-portable-anymap"	:	".pnm"	,
"application/vnd.macports.portpkg"	:	".portpkg"	,
"application/vnd.ms-powerpoint"	:	".pot"	,
"application/vnd.ms-powerpoint.template.macroenabled.12"	:	".potm"	,
"application/vnd.openxmlformats-officedocument.presentationml.template"	:	".potx"	,
"application/vnd.ms-powerpoint"	:	".ppa"	,
"application/vnd.ms-powerpoint.addin.macroenabled.12"	:	".ppam"	,
"application/vnd.cups-ppd"	:	".ppd"	,
"image/x-portable-pixmap"	:	".ppm"	,
"application/vnd.ms-powerpoint"	:	".pps"	,
"application/vnd.ms-powerpoint.slideshow.macroenabled.12"	:	".ppsm"	,
"application/vnd.openxmlformats-officedocument.presentationml.slideshow"	:	".ppsx"	,
"application/vnd.ms-powerpoint"	:	".ppt"	,
"application/vnd.ms-powerpoint.presentation.macroenabled.12"	:	".pptm"	,
"application/vnd.openxmlformats-officedocument.presentationml.presentation"	:	".pptx"	,
"application/vnd.palm"	:	".pqa"	,
"application/x-mobipocket-ebook"	:	".prc"	,
"application/vnd.lotus-freelance"	:	".pre"	,
"application/pics-rules"	:	".prf"	,
"application/postscript"	:	".ps"	,
"application/vnd.3gpp.pic-bw-small"	:	".psb"	,
"image/vnd.adobe.photoshop"	:	".psd"	,
"application/x-font-linux-psf"	:	".psf"	,
"application/vnd.pvi.ptid1"	:	".ptid"	,
"application/x-mspublisher"	:	".pub"	,
"application/vnd.3gpp.pic-bw-var"	:	".pvb"	,
"application/vnd.3m.post-it-notes"	:	".pwn"	,
"application/vnd.ms-powerpoint"	:	".pwz"	,
"text/x-python"	:	".py"	,
"audio/vnd.ms-playready.media.pya"	:	".pya"	,
"application/x-python-code"	:	".pyc"	,
"application/x-python-code"	:	".pyo"	,
"video/vnd.ms-playready.media.pyv"	:	".pyv"	,
"application/vnd.epson.quickanime"	:	".qam"	,
"application/vnd.intu.qbo"	:	".qbo"	,
"application/vnd.intu.qfx"	:	".qfx"	,
"application/vnd.publishare-delta-tree"	:	".qps"	,
"video/quicktime"	:	".qt"	,
"application/vnd.quark.quarkxpress"	:	".qwd"	,
"application/vnd.quark.quarkxpress"	:	".qwt"	,
"application/vnd.quark.quarkxpress"	:	".qxb"	,
"application/vnd.quark.quarkxpress"	:	".qxd"	,
"application/vnd.quark.quarkxpress"	:	".qxl"	,
"application/vnd.quark.quarkxpress"	:	".qxt"	,
"audio/x-pn-realaudio"	:	".ra"	,
"audio/x-pn-realaudio"	:	".ram"	,
"application/x-rar-compressed"	:	".rar"	,
"image/x-cmu-raster"	:	".ras"	,
"application/vnd.ipunplugged.rcprofile"	:	".rcprofile"	,
"application/rdf+xml"	:	".rdf"	,
"application/vnd.data-vision.rdz"	:	".rdz"	,
"application/vnd.businessobjects"	:	".rep"	,
"application/x-dtbresource+xml"	:	".res"	,
"image/x-rgb"	:	".rgb"	,
"application/reginfo+xml"	:	".rif"	,
"application/resource-lists+xml"	:	".rl"	,
"image/vnd.fujixerox.edmics-rlc"	:	".rlc"	,
"application/resource-lists-diff+xml"	:	".rld"	,
"application/vnd.rn-realmedia"	:	".rm"	,
"audio/midi"	:	".rmi"	,
"audio/x-pn-realaudio-plugin"	:	".rmp"	,
"application/vnd.jcp.javame.midlet-rms"	:	".rms"	,
"application/relax-ng-compact-syntax"	:	".rnc"	,
"text/troff"	:	".roff"	,
"application/x-rpm"	:	".rpm"	,
"application/vnd.nokia.radio-presets"	:	".rpss"	,
"application/vnd.nokia.radio-preset"	:	".rpst"	,
"application/sparql-query"	:	".rq"	,
"application/rls-services+xml"	:	".rs"	,
"application/rsd+xml"	:	".rsd"	,
"application/rss+xml"	:	".rss"	,
"application/rtf"	:	".rtf"	,
"text/richtext"	:	".rtx"	,
"text/x-asm"	:	".s"	,
"application/vnd.yamaha.smaf-audio"	:	".saf"	,
"application/sbml+xml"	:	".sbml"	,
"application/vnd.ibm.secure-container"	:	".sc"	,
"application/x-msschedule"	:	".scd"	,
"application/vnd.lotus-screencam"	:	".scm"	,
"application/scvp-cv-request"	:	".scq"	,
"application/scvp-cv-response"	:	".scs"	,
"text/vnd.curl.scurl"	:	".scurl"	,
"application/vnd.stardivision.draw"	:	".sda"	,
"application/vnd.stardivision.calc"	:	".sdc"	,
"application/vnd.stardivision.impress"	:	".sdd"	,
"application/vnd.solent.sdkm+xml"	:	".sdkd"	,
"application/vnd.solent.sdkm+xml"	:	".sdkm"	,
"application/sdp"	:	".sdp"	,
"application/vnd.stardivision.writer"	:	".sdw"	,
"application/vnd.seemail"	:	".see"	,
"application/vnd.fdsn.seed"	:	".seed"	,
"application/vnd.sema"	:	".sema"	,
"application/vnd.semd"	:	".semd"	,
"application/vnd.semf"	:	".semf"	,
"application/java-serialized-object"	:	".ser"	,
"application/set-payment-initiation"	:	".setpay"	,
"application/set-registration-initiation"	:	".setreg"	,
"application/vnd.hydrostatix.sof-data"	:	".sfd-hdstx"	,
"application/vnd.spotfire.sfs"	:	".sfs"	,
"application/vnd.stardivision.writer-global"	:	".sgl"	,
"text/sgml"	:	".sgm"	,
"text/sgml"	:	".sgml"	,
"application/x-sh"	:	".sh"	,
"application/x-shar"	:	".shar"	,
"application/shf+xml"	:	".shf"	,
"text/vnd.wap.si"	:	".si"	,
"application/vnd.wap.sic"	:	".sic"	,
"application/pgp-signature"	:	".sig"	,
"model/mesh"	:	".silo"	,
"application/vnd.symbian.install"	:	".sis"	,
"application/vnd.symbian.install"	:	".sisx"	,
"application/x-stuffit"	:	".sit"	,
"application/x-stuffitx"	:	".sitx"	,
"application/vnd.koan"	:	".skd"	,
"application/vnd.koan"	:	".skm"	,
"application/vnd.koan"	:	".skp"	,
"application/vnd.koan"	:	".skt"	,
"text/vnd.wap.sl"	:	".sl"	,
"application/vnd.wap.slc"	:	".slc"	,
"application/vnd.ms-powerpoint.slide.macroenabled.12"	:	".sldm"	,
"application/vnd.openxmlformats-officedocument.presentationml.slide"	:	".sldx"	,
"application/vnd.epson.salt"	:	".slt"	,
"application/vnd.stardivision.math"	:	".smf"	,
"application/smil+xml"	:	".smi"	,
"application/smil+xml"	:	".smil"	,
"audio/basic"	:	".snd"	,
"application/x-font-snf"	:	".snf"	,
"application/octet-stream"	:	".so"	,
"application/x-pkcs7-certificates"	:	".spc"	,
"application/vnd.yamaha.smaf-phrase"	:	".spf"	,
"application/x-futuresplash"	:	".spl"	,
"text/vnd.in3d.spot"	:	".spot"	,
"application/scvp-vp-response"	:	".spp"	,
"application/scvp-vp-request"	:	".spq"	,
"audio/ogg"	:	".spx"	,
"application/x-wais-source"	:	".src"	,
"application/sparql-results+xml"	:	".srx"	,
"application/vnd.kodak-descriptor"	:	".sse"	,
"application/vnd.epson.ssf"	:	".ssf"	,
"application/ssml+xml"	:	".ssml"	,
"application/vnd.sun.xml.calc.template"	:	".stc"	,
"application/vnd.sun.xml.draw.template"	:	".std"	,
"application/vnd.wt.stf"	:	".stf"	,
"application/vnd.sun.xml.impress.template"	:	".sti"	,
"application/hyperstudio"	:	".stk"	,
"application/vnd.ms-pki.stl"	:	".stl"	,
"application/vnd.pg.format"	:	".str"	,
"application/vnd.sun.xml.writer.template"	:	".stw"	,
"application/vnd.sus-calendar"	:	".sus"	,
"application/vnd.sus-calendar"	:	".susp"	,
"application/x-sv4cpio"	:	".sv4cpio"	,
"application/x-sv4crc"	:	".sv4crc"	,
"application/vnd.svd"	:	".svd"	,
"image/svg+xml"	:	".svg"	,
"image/svg+xml"	:	".svgz"	,
"application/x-director"	:	".swa"	,
"application/x-shockwave-flash"	:	".swf"	,
"application/vnd.arastra.swi"	:	".swi"	,
"application/vnd.sun.xml.calc"	:	".sxc"	,
"application/vnd.sun.xml.draw"	:	".sxd"	,
"application/vnd.sun.xml.writer.global"	:	".sxg"	,
"application/vnd.sun.xml.impress"	:	".sxi"	,
"application/vnd.sun.xml.math"	:	".sxm"	,
"application/vnd.sun.xml.writer"	:	".sxw"	,
"text/troff"	:	".t"	,
"application/vnd.tao.intent-module-archive"	:	".tao"	,
"application/x-tar"	:	".tar"	,
"application/vnd.3gpp2.tcap"	:	".tcap"	,
"application/x-tcl"	:	".tcl"	,
"application/vnd.smart.teacher"	:	".teacher"	,
"application/x-tex"	:	".tex"	,
"application/x-texinfo"	:	".texi"	,
"application/x-texinfo"	:	".texinfo"	,
"text/plain"	:	".text"	,
"application/x-tex-tfm"	:	".tfm"	,
"application/x-gzip"	:	".tgz"	,
"image/tiff"	:	".tif"	,
"image/tiff"	:	".tiff"	,
"application/vnd.tmobile-livetv"	:	".tmo"	,
"application/x-bittorrent"	:	".torrent"	,
"application/vnd.groove-tool-template"	:	".tpl"	,
"application/vnd.trid.tpt"	:	".tpt"	,
"text/troff"	:	".tr"	,
"application/vnd.trueapp"	:	".tra"	,
"application/x-msterminal"	:	".trm"	,
"text/tab-separated-values"	:	".tsv"	,
"application/x-font-ttf"	:	".ttc"	,
"application/x-font-ttf"	:	".ttf"	,
"application/vnd.simtech-mindmapper"	:	".twd"	,
"application/vnd.simtech-mindmapper"	:	".twds"	,
"application/vnd.genomatix.tuxedo"	:	".txd"	,
"application/vnd.mobius.txf"	:	".txf"	,
"text/plain"	:	".txt"	,
"application/x-authorware-bin"	:	".u32"	,
"application/x-debian-package"	:	".udeb"	,
"application/vnd.ufdl"	:	".ufd"	,
"application/vnd.ufdl"	:	".ufdl"	,
"application/vnd.umajin"	:	".umj"	,
"application/vnd.unity"	:	".unityweb"	,
"application/vnd.uoml+xml"	:	".uoml"	,
"text/uri-list"	:	".uri"	,
"text/uri-list"	:	".uris"	,
"text/uri-list"	:	".urls"	,
"application/x-ustar"	:	".ustar"	,
"application/vnd.uiq.theme"	:	".utz"	,
"text/x-uuencode"	:	".uu"	,
"application/x-cdlink"	:	".vcd"	,
"text/x-vcard"	:	".vcf"	,
"application/vnd.groove-vcard"	:	".vcg"	,
"text/x-vcalendar"	:	".vcs"	,
"application/vnd.vcx"	:	".vcx"	,
"application/vnd.visionary"	:	".vis"	,
"video/vnd.vivo"	:	".viv"	,
"application/vnd.stardivision.writer"	:	".vor"	,
"application/x-authorware-bin"	:	".vox"	,
"model/vrml"	:	".vrml"	,
"application/vnd.visio"	:	".vsd"	,
"application/vnd.vsf"	:	".vsf"	,
"application/vnd.visio"	:	".vss"	,
"application/vnd.visio"	:	".vst"	,
"application/vnd.visio"	:	".vsw"	,
"model/vnd.vtu"	:	".vtu"	,
"application/voicexml+xml"	:	".vxml"	,
"application/x-director"	:	".w3d"	,
"application/x-doom"	:	".wad"	,
"audio/x-wav"	:	".wav"	,
"audio/x-ms-wax"	:	".wax"	,
"image/vnd.wap.wbmp"	:	".wbmp"	,
"application/vnd.criticaltools.wbs+xml"	:	".wbs"	,
"application/vnd.wap.wbxml"	:	".wbxml"	,
"application/vnd.ms-works"	:	".wcm"	,
"application/vnd.ms-works"	:	".wdb"	,
"application/msword"	:	".wiz"	,
"application/vnd.ms-works"	:	".wks"	,
"video/x-ms-wm"	:	".wm"	,
"audio/x-ms-wma"	:	".wma"	,
"application/x-ms-wmd"	:	".wmd"	,
"application/x-msmetafile"	:	".wmf"	,
"text/vnd.wap.wml"	:	".wml"	,
"application/vnd.wap.wmlc"	:	".wmlc"	,
"text/vnd.wap.wmlscript"	:	".wmls"	,
"application/vnd.wap.wmlscriptc"	:	".wmlsc"	,
"video/x-ms-wmv"	:	".wmv"	,
"video/x-ms-wmx"	:	".wmx"	,
"application/x-ms-wmz"	:	".wmz"	,
"application/vnd.wordperfect"	:	".wpd"	,
"application/vnd.ms-wpl"	:	".wpl"	,
"application/vnd.ms-works"	:	".wps"	,
"application/vnd.wqd"	:	".wqd"	,
"application/x-mswrite"	:	".wri"	,
"model/vrml"	:	".wrl"	,
"application/wsdl+xml"	:	".wsdl"	,
"application/wspolicy+xml"	:	".wspolicy"	,
"application/vnd.webturbo"	:	".wtb"	,
"video/x-ms-wvx"	:	".wvx"	,
"application/x-authorware-bin"	:	".x32"	,
"application/vnd.hzn-3d-crossword"	:	".x3d"	,
"application/x-silverlight-app"	:	".xap"	,
"application/vnd.xara"	:	".xar"	,
"application/x-ms-xbap"	:	".xbap"	,
"application/vnd.fujixerox.docuworks.binder"	:	".xbd"	,
"image/x-xbitmap"	:	".xbm"	,
"application/vnd.syncml.dm+xml"	:	".xdm"	,
"application/vnd.adobe.xdp+xml"	:	".xdp"	,
"application/vnd.fujixerox.docuworks"	:	".xdw"	,
"application/xenc+xml"	:	".xenc"	,
"application/patch-ops-error+xml"	:	".xer"	,
"application/vnd.adobe.xfdf"	:	".xfdf"	,
"application/vnd.xfdl"	:	".xfdl"	,
"application/xhtml+xml"	:	".xht"	,
"application/xhtml+xml"	:	".xhtml"	,
"application/xv+xml"	:	".xhvml"	,
"image/vnd.xiff"	:	".xif"	,
"application/vnd.ms-excel"	:	".xla"	,
"application/vnd.ms-excel.addin.macroenabled.12"	:	".xlam"	,
"application/vnd.ms-excel"	:	".xlb"	,
"application/vnd.ms-excel"	:	".xlc"	,
"application/vnd.ms-excel"	:	".xlm"	,
"application/vnd.ms-excel"	:	".xls"	,
"application/vnd.ms-excel.sheet.binary.macroenabled.12"	:	".xlsb"	,
"application/vnd.ms-excel.sheet.macroenabled.12"	:	".xlsm"	,
"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"	:	".xlsx"	,
"application/vnd.ms-excel"	:	".xlt"	,
"application/vnd.ms-excel.template.macroenabled.12"	:	".xltm"	,
"application/vnd.openxmlformats-officedocument.spreadsheetml.template"	:	".xltx"	,
"application/vnd.ms-excel"	:	".xlw"	,
"application/xml"	:	".xml"	,
"application/vnd.olpc-sugar"	:	".xo"	,
"application/xop+xml"	:	".xop"	,
"application/xml"	:	".xpdl"	,
"application/x-xpinstall"	:	".xpi"	,
"image/x-xpixmap"	:	".xpm"	,
"application/vnd.is-xpr"	:	".xpr"	,
"application/vnd.ms-xpsdocument"	:	".xps"	,
"application/vnd.intercon.formnet"	:	".xpw"	,
"application/vnd.intercon.formnet"	:	".xpx"	,
"application/xml"	:	".xsl"	,
"application/xslt+xml"	:	".xslt"	,
"application/vnd.syncml+xml"	:	".xsm"	,
"application/xspf+xml"	:	".xspf"	,
"application/vnd.mozilla.xul+xml"	:	".xul"	,
"application/xv+xml"	:	".xvm"	,
"application/xv+xml"	:	".xvml"	,
"image/x-xwindowdump"	:	".xwd"	,
"chemical/x-xyz"	:	".xyz"	,
"application/vnd.zzazz.deck+xml"	:	".zaz"	,
"application/zip"	:	".zip"	,
"application/vnd.zul"	:	".zir"	,
"application/vnd.zul"	:	".zirz"	,
"application/vnd.handheld-entertainment+xml"	:	".zmm"	 
};
